version: '3'

services:

  php:
    build: docker/php-fpm
    container_name: ${PROJECT_NAME}-php
    working_dir: /app
    volumes:
      - ./app:/app

  webserver:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
