# Use the PHP 7.3 base image
FROM php:7.3-fpm

# Set the working directory inside the container
WORKDIR "/app"

# Instalar dependencias necesarias para Composer
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Download and install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create a basic composer.json file if it does not exist
RUN echo '{}' > composer.json

# Copy the content of the application to the working directory
COPY . "/app"

# Install PHP dependencies using Composer
RUN composer install

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Command to run PHP-FPM
CMD ["php-fpm"]
